delimiter $$

CREATE DATABASE `auction` /*!40100 DEFAULT CHARACTER SET utf8 */$$

delimiter $$

CREATE TABLE `accounts` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` tinytext,
  `ADDRESS` mediumtext,
  `PHONE` tinytext,
  `EMAIL` tinytext,
  `TAX_ID` tinytext,
  `BIDDER_ID` tinytext,
  `ACTIVE` bit(1) DEFAULT NULL,
  `CREATED` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=92 DEFAULT CHARSET=utf8$$

delimiter $$

CREATE TABLE `lots` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `TITLE` tinytext,
  `DESCRIPTION` text,
  `STATUS` tinytext,
  `DECLARED_VALUE` decimal(7,2) DEFAULT '0.00',
  `FINAL_VALUE` decimal(7,2) DEFAULT '0.00',
  `WINNER` int(11) DEFAULT NULL,
  `CONTRIBUTOR` int(11) DEFAULT NULL,
  `CREATED` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=158 DEFAULT CHARSET=utf8$$

delimiter $$

CREATE TABLE `payments` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ACCOUNT_ID` int(11) DEFAULT NULL,
  `AMOUNT` decimal(7,2) DEFAULT NULL,
  `INSTRUMENT` tinytext,
  `COMMENTS` mediumtext,
  `RECEIVED` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `MODIFIED` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `ID_idx` (`ACCOUNT_ID`),
  CONSTRAINT `ID` FOREIGN KEY (`ACCOUNT_ID`) REFERENCES `accounts` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8$$

